services:
  - type: web
    name: indore-colleges
    env: node
    plan: free
    branch: main
    rootDir: .
    installCommand: npm install
    buildCommand: npm run build
    startCommand: npm run start
    autoDeploy: true
